<?php echo "<?php\n" ?>

namespace <?php echo $namespace ?>\Type;
use FP\WHMCS\Entity;
use FP\WHMCS\Adapter\Connector;
use FP\WHMCS\Adapter\Response;
use FP\WHMCS\Adapter\Manager;

class <?php echo $className ?> extends Entity
{
  <?php foreach($fields as $fieldname => $field) : ?> 
  /**
   * @var <?php echo $field['type'] ?> 
   */ 
  protected $<?php echo $fieldname  ?>;
  <?php endforeach ?>
  <?php foreach($fields as $fieldname => $field) : ?> 
  /**
   * get <?php echo $fieldname ?> 
   * @return <?php echo $field['type'] ?> 
   */ 
  public function get<?php echo $field['as'] ?>()
  {
    return $this-><?php echo $fieldname ?>;
  }
  
  /**
   * set <?php echo $fieldname ?> 
   * @param <?php echo $field['type'] ?> $<?php echo $fieldname ?> 
   * @return <?php echo $className ?> 
   */ 
  public function set<?php echo $field['as'] ?>($fieldname)
  {
    $this-><?php echo $fieldname ?> = $<?php echo $fieldname ?>;
    return $this;
  }
  <?php endforeach ?> 
}